### ISSUE TITLE
flatpak runtime

### ISSUE THREAD

**Issue by bambukouk** [aandrew-me/ytDownloader#122]
I am using elementary OS 6.1 (ubuntu 20.04.5 LTS)
My system update insists that there is a component with update:
.me.aandrew.ytdownloader Flatpak runtime

but... whatever I do it doesn't happen?

I have uninstalled and re-installed YTdownloader buit it doesn't make any difference?

Can you help, please?

**Comment by aandrew-me** [comment]
Hello
I am sorry for your inconvenience. 

I had to change the app id and that's why you are getting that message. Its up-to Flathub to ensure a smooth transition of the app, however I see that you are facing problems.

So what I recommend to to is first uninstall Ytdownloader with old app ID
`flatpak remove me.aandrew.ytdownloader`

And then install -
`flatpak install flathub io.github.aandrew_me.ytdn`

**Comment by bambukouk** [comment]
That solved it - thank you :+1:
