### ISSUE TITLE
No videos from X (formerly Twitter) can be downloaded by Fedora 40 using the YT Downoader application

### ISSUE THREAD

**Issue by serial02** [aandrew-me/ytDownloader#215]
Hello

 No videos from X (formerly Twitter) can be downloaded by Fedora 40 using the Youtube Downloader Plus

![Captura de tela de 2024-05-18 13-18-40](https://github.com/aandrew-me/ytDownloader/assets/32621790/9d21b498-4a88-4e7b-92b1-091b62f6824f)
 application

**Comment by aandrew-me** [comment]
Hello, 
Well since the download part is handled by `yt-dlp`, its an issue on their side. For now you have to change x.com to twitter.com and it should work

**Comment by aandrew-me** [comment]
From next update the app will automatically handle this

**Comment by Mouldling** [comment]
The same issue is occurring on Chrome and firefox as it seems anything with twitter.com is getting re-written to x.com - so for example using some old saving twiiter.com links takes you to a x.com url and many fail as the resource (a search for example) hasn't crossed the divide. Your source update which simply rewrites the url from x.com to twitter.com is unlikely to work as a url rewrite already seems to occur on X. Do you have a working linux app image available you have tested yet?
A lot of tutorial videos and the like are moving to X rather than say youtube (better deal for producers?) so this issue is likely to grow.

**Comment by Mouldling** [comment]
OK, glad you have tested it. Personally I am finding the approach works a good proportion on the time in the app, but frustratingly does fail intermittently. If I try via the browser to check the change always seems to fail in a browser for me as twitter changes to x.com so investigating more will mean going deeper than I am able to at the moment.
 I'm glad the change works for you and presumably others who have built from source pending a fuller update, but I suspect the speed at which all aspects of twitter branding are changing you will /may need to make a change again soon when deeper changes are made. Sorry. Hope I'm wrong.
Any idea when the downloadable built app will be available as I do like your tool.

**Comment by serial02** [comment]
At the moment I have replaced x.com with twitter.com and it has worked.

 Downloads are carried out normally.

 We await the corrections.

**Comment by aandrew-me** [comment]
Should be working in latest release
